"""empty message

Revision ID: f055dd442d9
Revises: 2a2f3219d729
Create Date: 2016-09-03 08:32:41.838362

"""

# revision identifiers, used by Alembic.
revision = 'f055dd442d9'
down_revision = '2a2f3219d729'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_constraint(None, 'role')
    ### end Alembic commands ###
